version: '3.9'
services:
  postgres-db:
    image: 'postgres:15'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    environment:
      DJANGO_SUPERUSER_USERNAME: ${ADMIN_NAME}
      DJANGO_SUPERUSER_EMAIL: ${ADMIN_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${ADMIN_PASSWORD}
    command: >
      sh -c "
        cd /Store &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py createsuperuser --noinput &&
        python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      -  static_volume:/usr/src/app/static
      -  media_volume:/usr/Store/media

    depends_on:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  postgres-data:
  static_volume:
  media_volume: